# Generated by Django 2.2.10 on 2020-02-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectmoney',
            name='eshopAccount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intellectmoney',
            name='eshopId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intellectmoney',
            name='paymentData',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='intellectmoney',
            name='paymentId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
