# Generated by Django 4.0.5 on 2022-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectmoney', '0002_auto_20200211_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectmoney',
            name='reccurringState',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intellectmoney',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
